x-pawsitive-base: &pawsitive-base
  build: .
  ports:
    - ${PORT}:${PORT}

services:
  pawsitive-dev:
    <<: *pawsitive-base
    profiles: ["dev"]
    environment:
      - VITE_BACKEND_API=http://localhost:8000
    volumes:
      - .:/app # bind mount
      - /app/node_modules # so image node_modules not overwritten by local

  pawsitive-prod:
    <<: *pawsitive-base
    profiles: ["prod"]
    environment:
      - VITE_BACKEND_API=http://128.199.11.48:8000
