x-pawsitive-base: &pawsitive-base
  build: .
  ports:
    - ${PORT}:${PORT}

services:
  pawsitive-dev:
    <<: *pawsitive-base
    profiles: ["dev"]
    volumes:
      - .:/app  # bind mount
      - /app/node_modules  # so image node_modules not overwritten by local

  # prod config
  pawsitive-prod:
    <<: *pawsitive-base
    profiles: ["prod"]
    # no volumes
