x-pawsitive-base: &pawsitive-base
  build: .
  ports:
    - ${PORT}:${PORT}

services:
  pawsitive-dev:
    <<: *pawsitive-base
    profiles: ["dev"]
    env_file: ".env"
    volumes:
      - .:/app

  pawsitive-prod:
    <<: *pawsitive-base
    profiles: ["prod"]
    env_file: ".env" # TODO: .env shouldn't be used in prod, right now doesn't matter
    build:
      args:
        - TARGET_STAGE=${PROFILE}
