name: lint_test

on: pull_request

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Run linting
        run: make lint