# Generated by Django 5.2 on 2025-06-06 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placetype_place_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', related_query_name='place', to='places.placetype'),
        ),
    ]
