name: Frontend CI

on: pull_request

jobs:
  frontend_lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linting
        run: make lint
